apiVersion: v1
kind: Service
metadata:
  name: decision-server-svc
  labels:
    app: decision-server
spec:
  selector:
    app: decision-server
  ports:
    - name: http
      port: {{ .Values.decisionServer.port }}
      targetPort: {{ .Values.decisionServer.port }}
